

const fs = require('fs');
const path = require('path');

const catalogProducts = [
  // --- SHIRTS (8 items) ---
  {
    id: 1,
    name: 'Khaki Cargo Utility Shirt',
    category: 'Shirts',
    sku: 'TED-SH-001',
    price: 999,
    old_price: 1399,
    stock: 25,
    image: 'Shirts/images (10).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Rugged combed cotton utility shirt with dual chest flap cargo pockets and reinforced stitching.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 2,
    name: 'Floral Printed Resort Shirt',
    category: 'Shirts',
    sku: 'TED-SH-002',
    price: 899,
    old_price: 1299,
    stock: 20,
    image: 'Shirts/images (2).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Camp collar short-sleeve resort shirt with floral art and contrasting vertical graphic panels.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 3,
    name: 'Urban Graphic Printed Shirt',
    category: 'Shirts',
    sku: 'TED-SH-003',
    price: 949,
    old_price: 1349,
    stock: 22,
    image: 'Shirts/images (3).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Contemporary relaxed-fit graphic printed casual shirt with Cuban lapel collar and resort drape.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 4,
    name: 'Black Pleated Casual Shirt',
    category: 'Shirts',
    sku: 'TED-SH-004',
    price: 1099,
    old_price: 1599,
    stock: 18,
    image: 'Shirts/images (4).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Modern relaxed black shirt featuring elegant front vertical pleating and textured drape.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 5,
    name: 'Sky Blue Ombre Gradient Shirt',
    category: 'Shirts',
    sku: 'TED-SH-005',
    price: 899,
    old_price: 1249,
    stock: 30,
    image: 'Shirts/images (5).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Summer resort short-sleeve shirt with sky blue to white dip-dye ombre and neat camp collar.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 6,
    name: 'Sage Green Relaxed Linen Shirt',
    category: 'Shirts',
    sku: 'TED-SH-006',
    price: 1199,
    old_price: 1699,
    stock: 15,
    image: 'Shirts/images (7).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Breathable coastal sage green linen shirt with roll-up sleeve tabs and relaxed point collar.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 7,
    name: 'Dark Green Cotton Overshirt',
    category: 'Shirts',
    sku: 'TED-SH-007',
    price: 1049,
    old_price: 1499,
    stock: 24,
    image: 'Shirts/images (8).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Heavyweight forest green twill overshirt with utility flap chest pockets and tailored seams.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 8,
    name: 'Black & Royal Blue Gradient Shirt',
    category: 'Shirts',
    sku: 'TED-SH-008',
    price: 999,
    old_price: 1399,
    stock: 19,
    image: 'Shirts/images (9).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Tailored slim-fit evening shirt featuring a dip-dye black to cobalt blue gradient wash.',
    status: 1,
    new_arrival: 1
  },

  // --- T-SHIRTS (13 items) ---
  {
    id: 9,
    name: 'White Graphic Print Streetwear T-Shirt',
    category: 'T-Shirts',
    sku: 'TED-TS-001',
    price: 699,
    old_price: 949,
    stock: 35,
    image: 'T-shirts/images (17).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Heavyweight drop-shoulder white tee with vintage gold graphic artwork and ribbed collar.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 10,
    name: 'Royal Blue Oversized Graphic T-Shirt',
    category: 'T-Shirts',
    sku: 'TED-TS-002',
    price: 749,
    old_price: 1049,
    stock: 30,
    image: 'T-shirts/images (18).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Vibrant cobalt blue oversized streetwear t-shirt with back floral typography and relaxed drape.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 11,
    name: 'Cream Collegiate Oversized T-Shirt',
    category: 'T-Shirts',
    sku: 'TED-TS-003',
    price: 699,
    old_price: 999,
    stock: 28,
    image: 'T-shirts/images (19).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Boxy off-white collegiate varsity print crewneck t-shirt in heavy combed jersey.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 12,
    name: 'Maroon & Navy Striped Rugby Polo T-Shirt',
    category: 'T-Shirts',
    sku: 'TED-TS-004',
    price: 799,
    old_price: 1099,
    stock: 25,
    image: 'T-shirts/images (20).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Heritage colorblocked rugby polo tee with contrast white woven collar and chest embroidery.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 13,
    name: 'White Graffiti Typography Street T-Shirt',
    category: 'T-Shirts',
    sku: 'TED-TS-005',
    price: 649,
    old_price: 899,
    stock: 32,
    image: 'T-shirts/images (21).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Monochrome all-over graffiti typography artwork crewneck t-shirt with ribbed neck.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 14,
    name: 'Beige New York Graphic T-Shirt',
    category: 'T-Shirts',
    sku: 'TED-TS-006',
    price: 599,
    old_price: 849,
    stock: 30,
    image: 'T-shirts/images (22).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Soft combed oatmeal beige t-shirt with green collegiate varsity arch chest print.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 15,
    name: 'Retro Knit Zip-Collar Polo T-Shirt',
    category: 'T-Shirts',
    sku: 'TED-TS-007',
    price: 849,
    old_price: 1199,
    stock: 20,
    image: 'T-shirts/images (23).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Textured vertical cable knit polo shirt with front quarter zipper and tailored collar.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 16,
    name: 'Brown Long Sleeve Basketball T-Shirt',
    category: 'T-Shirts',
    sku: 'TED-TS-008',
    price: 699,
    old_price: 949,
    stock: 22,
    image: 'T-shirts/images (24).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Chocolate brown cotton jersey long-sleeve tee with vintage basketball graphic and ribbed cuffs.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 17,
    name: 'Brown Vintage Striped Knit Polo T-Shirt',
    category: 'T-Shirts',
    sku: 'TED-TS-009',
    price: 849,
    old_price: 1199,
    stock: 18,
    image: 'T-shirts/images (25).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Retro 70s vertical striped knit polo t-shirt with open Johnny collar and ribbed waist hem.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 18,
    name: 'Classic Red Crewneck T-Shirt',
    category: 'T-Shirts',
    sku: 'TED-TS-010',
    price: 549,
    old_price: 749,
    stock: 40,
    image: 'T-shirts/images (26).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Pure combed ring-spun cotton solid scarlet red crewneck t-shirt with durable seam finish.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 19,
    name: 'Black Waffle Knit Henley T-Shirt',
    category: 'T-Shirts',
    sku: 'TED-TS-011',
    price: 749,
    old_price: 999,
    stock: 26,
    image: 'T-shirts/images (27).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Textured thermal waffle knit long-sleeve Henley tee with four-button placket.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 20,
    name: 'Solid Brown Pique Polo T-Shirt',
    category: 'T-Shirts',
    sku: 'TED-TS-012',
    price: 699,
    old_price: 949,
    stock: 28,
    image: 'T-shirts/images (28).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Classic honeycombed pique knit polo t-shirt in rich mocha brown with two-button placket.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 21,
    name: 'White Graphic Slogan T-Shirt',
    category: 'T-Shirts',
    sku: 'TED-TS-013',
    price: 599,
    old_price: 799,
    stock: 35,
    image: 'T-shirts/images (29).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Clean white summer jersey t-shirt with bold retro chest slogan print and crew neck.',
    status: 1,
    new_arrival: 0
  },

  // --- TROUSERS (9 items) ---
  {
    id: 22,
    name: 'White Linen Formal Trousers',
    category: 'Trousers',
    sku: 'TED-TR-001',
    price: 1299,
    old_price: 1799,
    stock: 20,
    image: 'Trousers/2_4214be52-bd6e-493a-84ba-bfb0169fea43.webp',
    sizes: '30,32,34,36,38',
    description: 'Pristine white linen dress slacks with permanent pressed crease and tailored slash pockets.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 23,
    name: 'Black Slim Fit Formal Trousers',
    category: 'Trousers',
    sku: 'TED-TR-002',
    price: 1199,
    old_price: 1699,
    stock: 25,
    image: 'Trousers/images (42).jfif',
    sizes: '30,32,34,36,38',
    description: 'Tailored midnight black dress slacks in wrinkle-resistant poly-viscose blend with sharp crease.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 24,
    name: 'Dark Brown Wide Leg Relaxed Trousers',
    category: 'Trousers',
    sku: 'TED-TR-003',
    price: 1349,
    old_price: 1899,
    stock: 18,
    image: 'Trousers/images (43).jfif',
    sizes: '30,32,34,36,38',
    description: 'Fashion-forward wide-leg relaxed trousers in deep espresso brown with extended waist tabs.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 25,
    name: 'Royal Blue Slim Fit Dress Trousers',
    category: 'Trousers',
    sku: 'TED-TR-004',
    price: 1199,
    old_price: 1649,
    stock: 22,
    image: 'Trousers/images (44).jfif',
    sizes: '30,32,34,36,38',
    description: 'Sharp cobalt blue formal trousers tailored slim through the leg with interior waistband grip.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 26,
    name: 'Beige Textured Cotton Formal Trousers',
    category: 'Trousers',
    sku: 'TED-TR-005',
    price: 1099,
    old_price: 1499,
    stock: 24,
    image: 'Trousers/images (45).jfif',
    sizes: '30,32,34,36,38',
    description: 'Lightweight micro-textured sand beige trousers with flat front styling and clean hem.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 27,
    name: 'Off-White Relaxed Linen Trousers',
    category: 'Trousers',
    sku: 'TED-TR-006',
    price: 1249,
    old_price: 1749,
    stock: 17,
    image: 'Trousers/images (46).jfif',
    sizes: '30,32,34,36,38',
    description: 'Casual pleated linen-cotton trousers with elasticated waist in natural off-white.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 28,
    name: 'Olive Green Slim Fit Chinos',
    category: 'Trousers',
    sku: 'TED-TR-007',
    price: 1149,
    old_price: 1599,
    stock: 26,
    image: 'Trousers/images (47).jfif',
    sizes: '30,32,34,36,38',
    description: 'Military olive stretch cotton chinos featuring coin pocket and tapered ankle cut.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 29,
    name: 'Cream Slim Fit Casual Chinos',
    category: 'Trousers',
    sku: 'TED-TR-008',
    price: 1099,
    old_price: 1499,
    stock: 28,
    image: 'Trousers/images (6).jfif',
    sizes: '30,32,34,36,38',
    description: 'Clean ivory cream chinos woven with comfort stretch for versatile smart-casual wear.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 30,
    name: 'Khaki Loose Fit Linen Drawstring Trousers',
    category: 'Trousers',
    sku: 'TED-TR-009',
    price: 1299,
    old_price: 1799,
    stock: 19,
    image: 'Trousers/plustroulinloosep-khaki-1.webp',
    sizes: '30,32,34,36,38',
    description: 'Relaxed coastal khaki linen trousers with comfortable adjustable drawstring waistband.',
    status: 1,
    new_arrival: 0
  },

  // --- JEANS (8 items) ---
  {
    id: 31,
    name: 'Light Blue Distressed Ripped Jeans',
    category: 'Jeans',
    sku: 'TED-JN-001',
    price: 1499,
    old_price: 2099,
    stock: 16,
    image: 'jeans/901031801_g6.webp',
    sizes: '30,32,34,36,38',
    description: 'Bleached ice-blue denim jeans with artisanal knee rips and raw fraying details.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 32,
    name: 'Vintage Wash Relaxed Straight Jeans',
    category: 'Jeans',
    sku: 'TED-JN-002',
    price: 1399,
    old_price: 1899,
    stock: 20,
    image: 'jeans/images (11).jfif',
    sizes: '30,32,34,36,38',
    description: 'Authentic 90s vintage wash straight-leg blue denim jeans with classic 5-pocket styling.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 33,
    name: 'Classic Relaxed Fit Baggy Blue Jeans',
    category: 'Jeans',
    sku: 'TED-JN-003',
    price: 1349,
    old_price: 1799,
    stock: 22,
    image: 'jeans/images (12).jfif',
    sizes: '30,32,34,36,38',
    description: 'Medium indigo skater baggy denim with easy roomy thigh and straight leg opening.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 34,
    name: 'Heavy Distressed Grunge Denim Jeans',
    category: 'Jeans',
    sku: 'TED-JN-004',
    price: 1599,
    old_price: 2299,
    stock: 14,
    image: 'jeans/images (13).jfif',
    sizes: '30,32,34,36,38',
    description: 'Statement grunge destroyed blue jeans with layered fraying and distressing on thighs and knees.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 35,
    name: 'Classic Slim Fit Blue Denim Jeans',
    category: 'Jeans',
    sku: 'TED-JN-005',
    price: 1299,
    old_price: 1799,
    stock: 25,
    image: 'jeans/images (14).jfif',
    sizes: '30,32,34,36,38',
    description: 'Timeless clean blue denim with flexible comfort stretch and tailored slim leg contour.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 36,
    name: 'Light Blue Denim Jogger Jeans',
    category: 'Jeans',
    sku: 'TED-JN-006',
    price: 1399,
    old_price: 1949,
    stock: 18,
    image: 'jeans/images (15).jfif',
    sizes: '30,32,34,36,38',
    description: 'Elasticated drawstring waist light blue denim joggers with gathered cuffs and slash pockets.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 37,
    name: 'Camo Patch Distressed Tapered Jeans',
    category: 'Jeans',
    sku: 'TED-JN-007',
    price: 1449,
    old_price: 1999,
    stock: 19,
    image: 'jeans/images (16).jfif',
    sizes: '30,32,34,36,38',
    description: 'Dark wash distressed tapered jeans with reinforced camouflage backing patches behind knee tears.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 38,
    name: 'Washed Dark Grey Relaxed Jeans',
    category: 'Jeans',
    sku: 'TED-JN-008',
    price: 1399,
    old_price: 1899,
    stock: 21,
    image: 'jeans/jeanlswhsk-dgrey.webp',
    sizes: '30,32,34,36,38',
    description: 'Smoky charcoal grey enzyme-washed wide-leg denim jeans with clean modern finish.',
    status: 1,
    new_arrival: 1
  },

  // --- JACKETS (12 items) ---
  {
    id: 39,
    name: 'Brown Leather Aviator Bomber Jacket',
    category: 'Jackets',
    sku: 'TED-JK-001',
    price: 2699,
    old_price: 3799,
    stock: 10,
    image: 'jackets/images (30).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Genuine flight styling with plush shearling faux-fur collar, aviation badges, and zip sleeve pocket.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 40,
    name: 'Tan Suede Bomber Jacket',
    category: 'Jackets',
    sku: 'TED-JK-002',
    price: 2499,
    old_price: 3499,
    stock: 12,
    image: 'jackets/images (31).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Supple caramel tan suede bomber jacket with ribbed collar, hem, cuffs, and front zip closure.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 41,
    name: 'Distressed Brown Leather Field Jacket',
    category: 'Jackets',
    sku: 'TED-JK-003',
    price: 2899,
    old_price: 3999,
    stock: 8,
    image: 'jackets/images (32).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Vintage burnished brown leather coat with notched lapels, button front, and flap hip pockets.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 42,
    name: 'Burnished Brown Leather Zip Jacket',
    category: 'Jackets',
    sku: 'TED-JK-004',
    price: 2599,
    old_price: 3599,
    stock: 11,
    image: 'jackets/images (33).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Sleek front-zip burnished leather jacket with structured shirt collar and dual chest pockets.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 43,
    name: 'Camouflage Hooded Utility Parka',
    category: 'Jackets',
    sku: 'TED-JK-005',
    price: 2399,
    old_price: 3299,
    stock: 14,
    image: 'jackets/images (34).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'High-spec hooded camo utility jacket with technical weatherproofing and multi-compartment storage.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 44,
    name: 'Caramel Lightweight Bomber Jacket',
    category: 'Jackets',
    sku: 'TED-JK-006',
    price: 1999,
    old_price: 2799,
    stock: 16,
    image: 'jackets/images (35).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Clean minimalist caramel brown bomber jacket with smooth matte zip and ribbed trims.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 45,
    name: 'Olive Green Harrington Jacket',
    category: 'Jackets',
    sku: 'TED-JK-007',
    price: 2199,
    old_price: 2999,
    stock: 15,
    image: 'jackets/images (36).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Classic British Harrington silhouette with funnel collar, zip closure, and elasticated hem in army olive.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 46,
    name: 'Cream Suede Shearling Collar Jacket',
    category: 'Jackets',
    sku: 'TED-JK-008',
    price: 2799,
    old_price: 3899,
    stock: 9,
    image: 'jackets/images (37).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Warm ivory cream faux-suede jacket with cozy shearling fleece collar and neck buckle strap.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 47,
    name: 'Stonewash Blue Denim Trucker Jacket',
    category: 'Jackets',
    sku: 'TED-JK-009',
    price: 1899,
    old_price: 2599,
    stock: 18,
    image: 'jackets/images (38).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Heritage medium blue denim trucker jacket with dual chest flap pockets and shank buttons.',
    status: 1,
    new_arrival: 0
  },
  {
    id: 48,
    name: 'Washed Grey Leather Moto Jacket',
    category: 'Jackets',
    sku: 'TED-JK-010',
    price: 2499,
    old_price: 3499,
    stock: 12,
    image: 'jackets/images (39).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Distressed acid-wash grey leather jacket with biker mandarin collar and dual chest flap pockets.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 49,
    name: 'Speed Racing Biker Leather Jacket',
    category: 'Jackets',
    sku: 'TED-JK-011',
    price: 2999,
    old_price: 4299,
    stock: 7,
    image: 'jackets/images (40).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Colorblocked black and white leather motorcycle jacket with racing badges and snap collar.',
    status: 1,
    new_arrival: 1
  },
  {
    id: 50,
    name: 'Scuba Suede Oversized Contrast Jacket',
    category: 'Jackets',
    sku: 'TED-JK-012',
    price: 2299,
    old_price: 3199,
    stock: 13,
    image: 'jackets/images (41).jfif',
    sizes: 'S,M,L,XL,XXL',
    description: 'Modern drop-shoulder cream and olive contrast scuba suede jacket with asymmetric biker zipper.',
    status: 1,
    new_arrival: 1
  }
];

// 1. Update data.json
const dataPath = path.join(__dirname, 'data.json');
let data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));
data.products = catalogProducts;
fs.writeFileSync(dataPath, JSON.stringify(data, null, 2), 'utf8');
console.log('data.json successfully updated with 50 products!');

// 2. Update database.sql
const sqlValues = catalogProducts.map(p => {
  const escName = p.name.replace(/'/g, "''");
  const escDesc = p.description.replace(/'/g, "''");
  return `('${escName}', '${p.category}', '${p.sku}', ${p.price}, ${p.old_price}, ${p.stock}, '${p.image}', '${escDesc}', 1, ${p.new_arrival}, '${p.sizes}')`;
}).join(',\n');

const sqlPath = path.join(__dirname, 'database.sql');
let sqlFile = fs.readFileSync(sqlPath, 'utf8');
const insertStart = sqlFile.indexOf('INSERT INTO `products`');
if (insertStart !== -1) {
  const pre = sqlFile.substring(0, insertStart);
  const newInsert = `INSERT INTO \`products\` (\`name\`, \`category\`, \`sku\`, \`price\`, \`old_price\`, \`stock\`, \`image\`, \`description\`, \`status\`, \`new_arrival\`, \`sizes\`) VALUES\n${sqlValues};\n`;
  fs.writeFileSync(sqlPath, pre + newInsert, 'utf8');
  console.log('database.sql successfully updated with 50 product seeds!');
}

console.log('Catalog verification:');
console.log('Total:', catalogProducts.length);
const counts = {};
catalogProducts.forEach(p => counts[p.category] = (counts[p.category] || 0) + 1);
console.log('Category breakdown:', counts);
